# Generated by Django 3.1 on 2020-08-27 01:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelinePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('timeline_item', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(help_text='enter the date that the event happened on', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='name the event here', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='insert an image to go with your event (optional)', required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='describe the event here', required=True))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
