# Generated by Django 3.1 on 2020-08-27 12:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinepage',
            name='body',
            field=wagtail.core.fields.StreamField([('timeline_item', wagtail.core.blocks.StructBlock([('timeline_item', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(help_text='enter the date that the event happened on', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='name the event here', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='insert an image to go with your event (optional)', required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='describe the event here', required=True)), ('item_page', wagtail.core.blocks.PageChooserBlock(help_text='use if you want to link item to another page', required=False)), ('item_url', wagtail.core.blocks.URLBlock(help_text='use if you want to go to external links', required=False))])))]))], blank=True, null=True),
        ),
    ]
